- name: Capture ctop version
  shell: ctop -v | awk '{print $3}' | sed 's/,//g'
  register: ctop
  changed_when: False

- name: Install ctop
  become: yes
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v{{ ctop_version }}/ctop-{{ ctop_version }}-linux-amd64
    dest: /usr/local/bin/ctop
    owner: root
    group: root
    mode: 755
  when: ctop.stdout != ctop_version
