- name: Install gopass (Arch)
  become: yes
  pacman:
    name: gopass
  when: ansible_distribution == "Archlinux"

- name: Install gopass apt key (Ubuntu)
  become: yes
  apt_key:
    url: https://api.bintray.com/orgs/gopasspw/keys/gpg/public.key
  when: ansible_distribution == "Ubuntu"

- name: Install gopass apt repository (Ubuntu)
  become: yes
  apt_repository:
    repo: deb https://dl.bintray.com/gopasspw/gopass trusty main
  when: ansible_distribution == "Ubuntu"

- name: Install gopass (Ubuntu)
  become: yes
  apt:
    name: 
    - gopass
    - xclip
  when: ansible_distribution == "Ubuntu"
